// ignore_for_file: constant_identifier_names

const app_name = "APES";
const font_bold = "theme2fonts/googlesansbold.ttf";
const font_medium = "theme2fonts/googlesansMedium.ttf";
const font_regular = "theme2fonts/googlesansregular.ttf";
const font_semi_bold = "theme2fonts/googlesansMedium.ttf";
const lbl_sign_in_header = "Sign In/";
const lbl_sign_up_header = "Sign Up/";
const lbl_sign_up = "Sign Up";
const hint_email = "Email";
const hint_phone = "Phone Number";
const country_code = "+91 ";
const lbl_already = "Already have an account ? ";
const lbl_fullName = "Full Name";
const lbl_state = "State";
const lbl_newUser = "New User ? ";
const hint_password = "Password";
const verify_otp = "Verify OTP";
const opt_confirm = "Confirm";
const otp_note = "Please enter code that sent to your phone number ";
const resend = "Resend";
const lbl_remember = "Remember";
const lbl_sign_in = "Sign In";
const lbl_forgot_password = "Forgot Password?";
const hint_re_password = "Re-Password";
const lbl_all = "All";
const lbl_Popular = "Popular";
const lbl_new = "New";
const lbl_trend = "Trend";
const s =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.";
const lbl_get_started = "Get Started";
const lbl_personal = "Personal";
const hint_userName = "User Name";
const profile_userName = "Aston Cina";
const profile_email = "Astoncina@gmail.com";
const profile_address = "South poul, Less Vegas street. \n396568 ";
const lbl_contacts = "Contacts";
const profile_contactNo = "+91 53464568346";
const hint_contact = "Contact";
const lbl_save = "Save";
const edit_cover_photo = "Edit Cover Photo";
const lbl_walkthrough = "Walkthrough";
const lbl_sry = "Sorry!";
const lbl_welcome_to_bottom_n_navigation_baar =
    "Welcome to Bottom Navigation Bar";
const lbl_welcome_to_bottom_n_navigation_bar1 = "Welcome to Navigation Bar";
const lbl_share_to = "Share to";
const text_todo = "TODO";
const open = "Open";
const close = "Close";
const lbl_see_your_favourite = "See Your Favourite";
const lbl_view_all = "View all";
const slider_title = "Image Slider";
const sample_text =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.";
const lbl_dashboard = "Dashboard";
const lbl_profile = "Profile";
const lbl_notification = "Notification";
const lbl_favourite = "Favourite";
const lbl_home = "Home";
const lbl_welcome_to_bottom_n_navigation_bar =
    "Welcome to Bottom \nNavigation Bar";
const lbl_welcome_to_search_bar = "Welcome to Search \n Bar";
const lbl_search = "Search";
const lbl_try_again = "Try again";
const lbl_welcome_to_bottom_n_sheet = "Welcome to Bottom \n  Sheet";
const lbl_message = "Message";
const lbl_report = "Report";
const lbl_settings = "Settings";
const lbl_sign_out = "Sign Out";
const lbl_share_and_invite = "Share and Invite";
const lbl_help_and_feedback = "Help and Feedback";
const user_email = "johnvilla@gmail.com";
const user_name = "John Villa";
const samplelong_text =
    "Lorem Ipsum is simply dummy text of the printing and typesetting industry.simply duumy text ";
const lbl_cards = "Cards";
const lbl_dialog = "Dialog";
const usable_flower_for_health = "Usable Flower for Health";
const read = "Read";

const bottom_navigation = "Bottom Navigation";
const Listing = "Listing";
const Cards = "Cards";
const Dialog = "Dialog";
const Bottom_Sheet = "Bottom Sheet";
const Image_Slider = "Image Slider";
